name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'demos/react-vite/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd demos/react-vite
        npm ci
        
    - name: Build React + Vite demo
      run: |
        cd demos/react-vite
        npm run build
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Create deployment structure
      run: |
        mkdir -p _site
        
        # Copy all demos to deployment directory
        cp -r demos/ _site/demos/
        
        # Copy documentation
        cp -r docs/ _site/docs/
        
        # Copy root files
        cp README.md _site/
        cp LICENSE _site/ 2>/dev/null || echo "LICENSE file not found, skipping"
        
        # Create index.html that redirects to README
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>ModernToasts Demo</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    max-width: 1200px;
                    margin: 0 auto;
                    padding: 2rem;
                    line-height: 1.6;
                    color: #333;
                }
                .demo-grid {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 2rem;
                    margin: 2rem 0;
                }
                .demo-card {
                    border: 1px solid #e1e5e9;
                    border-radius: 8px;
                    padding: 1.5rem;
                    background: #fff;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                    transition: transform 0.2s;
                }
                .demo-card:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 4px 8px rgba(0,0,0,0.15);
                }
                .demo-title {
                    margin: 0 0 1rem 0;
                    color: #2563eb;
                }
                .demo-description {
                    color: #6b7280;
                    margin-bottom: 1rem;
                }
                .demo-links {
                    display: flex;
                    gap: 1rem;
                }
                .demo-link {
                    display: inline-block;
                    padding: 0.5rem 1rem;
                    background: #2563eb;
                    color: white;
                    text-decoration: none;
                    border-radius: 4px;
                    font-size: 0.9rem;
                    transition: background 0.2s;
                }
                .demo-link:hover {
                    background: #1d4ed8;
                }
                .demo-link.secondary {
                    background: #6b7280;
                }
                .demo-link.secondary:hover {
                    background: #4b5563;
                }
                .header {
                    text-align: center;
                    margin-bottom: 3rem;
                }
                .badge {
                    display: inline-block;
                    padding: 0.25rem 0.5rem;
                    background: #10b981;
                    color: white;
                    border-radius: 4px;
                    font-size: 0.8rem;
                    margin-left: 0.5rem;
                }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🍞 ModernToasts Demo</h1>
                <p>A comprehensive showcase of modern stacked overlay toast notification implementations</p>
            </div>
            
            <div class="demo-grid">
                <div class="demo-card">
                    <h3 class="demo-title">Pure Vanilla JS/CSS <span class="badge">No Build</span></h3>
                    <p class="demo-description">Pure implementation with no dependencies. Perfect for learning and lightweight projects.</p>
                    <div class="demo-links">
                        <a href="./demos/pure-vanilla-css-js/" class="demo-link">🚀 Live Demo</a>
                        <a href="./demos/pure-vanilla-css-js/README.md" class="demo-link secondary">📖 Docs</a>
                    </div>
                </div>
                
                <div class="demo-card">
                    <h3 class="demo-title">React + Vanilla CSS <span class="badge">No Build</span></h3>
                    <p class="demo-description">React components with custom CSS. Component-based architecture with custom styling.</p>
                    <div class="demo-links">
                        <a href="./demos/react-vanilla-css/" class="demo-link">🚀 Live Demo</a>
                        <a href="./demos/react-vanilla-css/README.md" class="demo-link secondary">📖 Docs</a>
                    </div>
                </div>
                
                <div class="demo-card">
                    <h3 class="demo-title">React + Tailwind CSS <span class="badge">No Build</span></h3>
                    <p class="demo-description">React with Tailwind CSS. Utility-first CSS framework for rapid development.</p>
                    <div class="demo-links">
                        <a href="./demos/react-tailwind-css/" class="demo-link">🚀 Live Demo</a>
                        <a href="./demos/react-tailwind-css/README.md" class="demo-link secondary">📖 Docs</a>
                    </div>
                </div>
                
                <div class="demo-card">
                    <h3 class="demo-title">React + Vite + TypeScript <span class="badge">Built</span></h3>
                    <p class="demo-description">Modern development setup with TypeScript, Vite, and optimized builds.</p>
                    <div class="demo-links">
                        <a href="./demos/react-vite/dist/" class="demo-link">🚀 Live Demo</a>
                        <a href="./demos/react-vite/README.md" class="demo-link secondary">📖 Docs</a>
                    </div>
                </div>
            </div>
            
            <div style="text-align: center; margin-top: 3rem;">
                <h2>📚 Documentation</h2>
                <div style="display: flex; justify-content: center; gap: 1rem; flex-wrap: wrap;">
                    <a href="./docs/api-reference.md" class="demo-link secondary">API Reference</a>
                    <a href="./docs/implementation-comparison.md" class="demo-link secondary">Implementation Comparison</a>
                    <a href="./docs/build-instructions.md" class="demo-link secondary">Build Instructions</a>
                </div>
            </div>
            
            <footer style="text-align: center; margin-top: 3rem; padding-top: 2rem; border-top: 1px solid #e1e5e9; color: #6b7280;">
                <p>Made with ❤️ by Sukarth Acharya | <a href="https://github.com/yourusername/ModernToasts-demo" style="color: #2563eb;">View on GitHub</a></p>
            </footer>
        </body>
        </html>
        EOF
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4